AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  MyBucketName:
    Description: 'The name of the S3 bucket'
    Type: String

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName:
        Ref: MyBucketName
