AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates buckets.
Metadata:
  LICENSE: Apache License, Version 2.0
  QuickStartDocumentation:
    EntrypointName: Launch TDG Dev Stack
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required Parameters
        Parameters:
          - TemplateBucketURL
    ParameterLabels:
      TemplateBucketURL:
        default: Bucket template location
Parameters:
  TemplateBucketURL:
    Type: String
    Description: >-
      Path to CloudFormation template `.yaml` file, in S3 bucket.
    ConstraintDescription: >-
      Must be a valid AWS Bucket URL.
Resources:
  FirstNestedBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateBucketURL
      Parameters:
        MyBucketName: "dave-test-bucket-u38f74hd93"
  SecondNestedBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateBucketURL
      Parameters:
        MyBucketName: !GetAtt FirstNestedBucket.Outputs.ConcatenatedBucketName