AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates the dev stack for project TDG:
  * VPC, etc.
  * Cloud9 environments for developers
Metadata:
  LICENSE: Apache License, Version 2.0
  QuickStartDocumentation:
    EntrypointName: Launch TDG Dev Stack
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Required Parameters
        Parameters:
          - TemplateBucketURL
    ParameterLabels:
      TemplateBucketURL:
        default: Template Bucket URL
Parameters:
  TemplateBucketURL:
    Type: String
    Description: >-
      Path to VPC CloudFormation template `.yaml` file, in S3 bucket.
    AllowedPattern: >-
      ^https://.*\.yaml$
    ConstraintDescription: >-
      Must be a valid AWS Bucket URL.
Resources:
  MyNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateBucketURL
      Parameters:
        AvailabilityZones: ['eu-west-2a', 'eu-west-2b']